#if !canImport(ObjectiveC)
  import XCTest

  extension CalmTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CalmTests = [
      ("testExample", testExample)
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    [
      testCase(CalmTests.__allTests__CalmTests)
    ]
  }
#endif
