#if !canImport(ObjectiveC)
import XCTest

extension CalmKitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CalmKitTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CalmKitTests.__allTests__CalmKitTests),
    ]
}
#endif
